### ISSUE TITLE
diagnostic plots not working

### ISSUE THREAD

**Issue by ptrebert** [daewoooo/SaaRclust#13]
Using commit `f4d963e`, the diagnostic plots (`plotClusteredContigs`: clustering, ordering, orienting) are not working:

```
Error in seq.int(from = start^gamma, to = end^gamma, length.out = n) : 
  'length.out' must be a non-negative number
Calls: plotClusteredContigs -> gray.colors -> gray
In addition: Warning message:
Expected 3 pieces. Missing pieces filled with `NA` in 757 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]. 
Execution halted
```

**Comment by daewoooo** [comment]
Can you please share with me the BED file of mapped contigs to GRCh38 you were trying to plot???

**Comment by ptrebert** [comment]
Tested now, works.
For documentation: if parameter `concat.fasta` is set to `TRUE`, ordering information is not preserved, and hence, the `ordering` plot cannot be produced.

Suggestion for the far future: renaming `concat.fasta` to `concat.contigs` or `single.sequence` might help understanding what this parameter is doing
