### ISSUE TITLE
missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by ptrebert** [daewoooo/SaaRclust#14]
version `71b3763`

```
Error in if (!all(chrom.lengths == GenomeInfoDb::seqlengths(fa.idx)[names(chrom.lengths)])) { : 
  missing value where TRUE/FALSE needed
Calls: scaffoldDenovoAssembly
Execution halted
```
Note that all input FASTAs have an index file (same path with extension `.fai`)

**Comment by daewoooo** [comment]
I have replicated the error and fixed it! Now when this happens assembly.fasta parameter is set to NULL and no FASTA is reported.
