### ISSUE TITLE
diagnostic plot not working

### ISSUE THREAD

**Issue by ptrebert** [daewoooo/SaaRclust#16]
https://github.com/daewoooo/SaaRclust/blob/9b4aa007212c61685b483e58b5487cafe9c5cce7/R/plotting.R#L379

the above line raises an error, the object "plt" is unknown in this context; seems to happen when contig ordering is plotted

**Comment by ptrebert** [comment]
```R
Error in is.ggplot(plt) : object 'plt' not found
Calls: plotClusteredContigs -> is.ggplot
```
what about this one, David? Still not working...

**Comment by daewoooo** [comment]
I have checked and encode this function as ggplot2::is.ggplot. It should have now proper function scoping. Try reinstall updated github version.

**Comment by ptrebert** [comment]
could you confirm this in some way, because updating software in active pipeline runs is a bit annoying...

**Comment by daewoooo** [comment]
Yes I understand. I will test it and let you know ASAP.

**Comment by daewoooo** [comment]
I had rerun updated SaaRclust diagnostig plotting and it worked well on my system.

**Comment by ptrebert** [comment]
Thanks, but apparently, that wasn't it...
I noticed that there is a message before the error that is probably hinting at the actual error:
https://github.com/daewoooo/SaaRclust/blob/9b4aa007212c61685b483e58b5487cafe9c5cce7/R/plotting.R#L359
My guess is that "order" is not part of the column names in the data frame, and this line evaluates to FALSE:
https://github.com/daewoooo/SaaRclust/blob/d51c66f78b788fa60abe57033ff3071e2637de68/R/plotting.R#L331
I don't find the place in the code where "order" is added to `plt.df`, though...

Edit: for the record, SaaRclust is configured with `concat.fasta = FALSE` in the final clustering step - it is my understanding that this is sufficient for the `ordering` diagnostic plot to work properly

**Comment by ptrebert** [comment]
I implemented the workaround as discussed, but I still get the same error. The name field in the BED now looks like this:
```
cluster13_scaffold-12_15_cluster2
cluster13_contig-35_19_cluster2
```
why does that not work?

**Comment by daewoooo** [comment]
Hmm this is weird. I can have a look at your BED file to see what is wrong so I can better debug my code.

**Comment by ptrebert** [comment]
ok, this was just a problem in my script, fixed now
