### ISSUE TITLE
diagnostic plot not working

### ISSUE THREAD

**Issue by ptrebert** [daewoooo/SaaRclust#17]
Hi David,

this is probably easy to fix (latest dev commit):

```R
Error in (function (el, elname)  : 
  "strip.text.y.left" is not a valid theme element name.
Calls: plotClusteredContigs -> theme -> mapply -> <Anonymous>
```

**Comment by daewoooo** [comment]
I think this error is caused by the change in ggplot2 package. Current setting expects ggplot2 version 3.3.0. Perhaps try to update this package. If this package works for you I can encode this version as an requirement when installing the package.

**Comment by ptrebert** [comment]
ggplot2 v3.3.0 solves the issue
